cc.SPRITE_DEBUG_DRAW =  1;

GAME = {};
GAME.SCORE=0;
GAME.LIFES=3;
GAME.SOUND=true;
GAME.LASTLEVEL=null;
GAME.SCROLLING = {
	SPEED_X: 180,
	TOTAL: 0,
};

//container
GAME.CONTAINER = {
    ENEMIES:[],
    ENEMIES_BULLETS:[],
    PLAYER_BULLETS:[]
};
