cc.SPRITE_DEBUG_DRAW =  0;

GAME = {};
GAME.SCORE=0;
GAME.LIFES=3;
GAME.SOUND=true;
GAME.LASTLEVEL=null;
GAME.GROUND_HEIGHT_PERC=0.11;
GAME.SCROLLING = {
	SPEED_X: 300,
	TOTAL: 0,
};

//container
GAME.CONTAINER = {
    ENEMIES:[],
    ENEMIES_BULLETS:[],
    PLAYER_BULLETS:[]
};
